// vocab_extra.js — Extra vocabulary additions (CodingFriends de-en lists)
// Source repo: https://github.com/CodingFriends/basic-vocabulary-word-lists
// License: CC BY-NC 4.0 (NonCommercial). Ensure your use complies.
//
// This file exists to make the expanded vocab count work permanently,
// even when opening `index.html` via file:// (where IndexedDB imports may not persist).

window.VOCAB_EXTRA_DB = [
  { id: 1188, de: "zusammen", en: "together", level: "A1", type: "adjective", tags: ["basic","adjective"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1189, de: "getrennt", en: "separate", level: "A1", type: "adjective", tags: ["basic","adjective"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1190, de: "bunt", en: "colorful", level: "A1", type: "noun", tags: ["basic","color"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1191, de: "Hallo!", en: "Hi!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1192, de: "Guten Tag!", en: "Hello!", level: "A1", type: "phrase", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1193, de: "Tschüß!", en: "Goodbye! / Bye!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1194, de: "Danke!", en: "Thank you!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1195, de: "Bitte!", en: "Please!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1196, de: "Entschuldigung!", en: "Sorry!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1197, de: "Stopp!", en: "Stop!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1198, de: "Vorsicht!", en: "Caution!", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1199, de: "ja", en: "yes", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1200, de: "nein", en: "no", level: "A1", type: "noun", tags: ["basic","communication"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1201, de: "Café", en: "café", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "das" },
  { id: 1202, de: "Speisekarte", en: "menu", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1203, de: "Vorspeise", en: "starter", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1204, de: "Hauptspeise", en: "main course", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1205, de: "Nachtisch", en: "dessert", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1206, de: "vegetarisch", en: "vegetarian", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1207, de: "vegan", en: "vegan", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1208, de: "glutenfrei", en: "gluten-free", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1209, de: "Nüsse", en: "nuts", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1210, de: "alkoholfrei", en: "non-alcoholic", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1211, de: "Prost!", en: "Cheers!", level: "A1", type: "noun", tags: ["basic","food"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1212, de: "Arzt / Ärztin", en: "doctor", level: "A1", type: "noun", tags: ["basic","health"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1213, de: "Schmerzmittel", en: "painkiller", level: "A1", type: "noun", tags: ["basic","health"], source: "CodingFriends/basic-vocabulary-word-lists", article: "das" },
  { id: 1214, de: "Schmerzen", en: "pain", level: "A1", type: "noun", tags: ["basic","health","body"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1215, de: "Rücken", en: "back", level: "A1", type: "noun", tags: ["basic","health","body"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1216, de: "Bauch", en: "stomach", level: "A1", type: "noun", tags: ["basic","health","body"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1217, de: "Richtung", en: "direction", level: "A1", type: "noun", tags: ["basic","orientation"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1218, de: "Eingang", en: "entrance", level: "A1", type: "noun", tags: ["basic","orientation"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1219, de: "Ausgang", en: "exit", level: "A1", type: "noun", tags: ["basic","orientation"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1220, de: "zurück", en: "back", level: "A1", type: "noun", tags: ["basic","orientation"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1221, de: "Adresse", en: "address", level: "A1", type: "noun", tags: ["basic","personal-information"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1222, de: "Geburtsort", en: "place of birth", level: "A1", type: "noun", tags: ["basic","personal-information"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1223, de: "Geburtsdatum", en: "date of birth", level: "A1", type: "noun", tags: ["basic","personal-information"], source: "CodingFriends/basic-vocabulary-word-lists", article: "das" },
  { id: 1224, de: "Erwachsene(r)", en: "adult", level: "A1", type: "noun", tags: ["basic","personal-information"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1225, de: "Was ist …?", en: "What is …?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1226, de: "Wo ist …?", en: "Where is …?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1227, de: "Wie …?", en: "How …?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1228, de: "Wie viel kostet es?", en: "How much is it?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1229, de: "Wie lange dauert es?", en: "How long does it take?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1230, de: "Gibt es …?", en: "Is there …?", level: "A1", type: "phrase", tags: ["basic","sentences","questions"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1231, de: "Ich hätte gerne …", en: "I would like ...", level: "A1", type: "phrase", tags: ["basic","sentences"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1232, de: "Ich brauche …", en: "I need ...", level: "A1", type: "phrase", tags: ["basic","sentences"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1233, de: "Kein Problem!", en: "No problem!", level: "A1", type: "phrase", tags: ["basic","sentences"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1234, de: "Supermarkt", en: "supermarket", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1235, de: "Karte (Bankkarte)", en: "bank card", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1236, de: "Tampon", en: "tampon", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1237, de: "Binde", en: "(sanitary) pad", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1238, de: "Kondom", en: "condom", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "das" },
  { id: 1239, de: "Hilfe", en: "help", level: "A1", type: "noun", tags: ["basic","shopping"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1240, de: "Steckdose", en: "socket", level: "A1", type: "noun", tags: ["basic","technology"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1241, de: "morgens", en: "in the morning", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1242, de: "nachmittags", en: "in the afternoon", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1243, de: "abends", en: "in the evening", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1244, de: "nachts", en: "at night", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1245, de: "früher", en: "earlier", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1246, de: "verspätet", en: "delayed", level: "A1", type: "noun", tags: ["basic","time"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1247, de: "Straßenbahn", en: "tram", level: "A1", type: "noun", tags: ["basic","transport"], source: "CodingFriends/basic-vocabulary-word-lists", article: "die" },
  { id: 1248, de: "Taxi", en: "taxi, cab", level: "A1", type: "noun", tags: ["basic","transport"], source: "CodingFriends/basic-vocabulary-word-lists", article: "das" },
  { id: 1249, de: "zu Fuß", en: "on foot", level: "A1", type: "phrase", tags: ["basic","transport"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1250, de: "Busbahnhof", en: "bus station", level: "A1", type: "noun", tags: ["basic","transport"], source: "CodingFriends/basic-vocabulary-word-lists", article: "der" },
  { id: 1251, de: "besuchen", en: "to visit", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1252, de: "brauchen", en: "to need", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1253, de: "fragen", en: "to ask", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1254, de: "haben", en: "to have", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1255, de: "kaufen", en: "to buy", level: "A1", type: "verb", tags: ["basic","verb","shopping"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1256, de: "sagen", en: "to say", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1257, de: "schreiben", en: "to write", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1258, de: "sehen", en: "to see", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1259, de: "sein", en: "to be", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1260, de: "suchen", en: "to search", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1261, de: "telefonieren", en: "to call", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1262, de: "trinken", en: "to drink", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1263, de: "wissen", en: "to know", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" },
  { id: 1264, de: "zahlen", en: "to pay", level: "A1", type: "verb", tags: ["basic","verb"], source: "CodingFriends/basic-vocabulary-word-lists" }
];

